version: '3.7'
configs:
  TON.env:
    file: .env
services:       
  swarm-visualizer:  
    image: dockersamples/visualizer  
    ports:
      - 8080:${VIZ_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role==manager
  gram:  
    configs:
      - TON.env
    image: ${IMAGEURI}
    command: gram launch wait
    ports:
      - ${TON_OUTGOING}:${TON_OUTGOING}
      - ${TON_OUTGOING}:${TON_OUTGOING}/udp
      - ${TON_ENGINE_PORT}:${TON_ENGINE_PORT}
      - ${TON_ENGINE_PORT}:${TON_ENGINE_PORT}/udp
      - ${LITESERVER_PORT}:${LITESERVER_PORT}
      - ${CONSOLE_PORT}:${CONSOLE_PORT}
      - ${WEB_EXPLORER_PORT}:${WEB_EXPLORER_PORT}
      - ${JSON_EXPLORER_PORT}:${JSON_EXPLORER_PORT}
      - ${GRAM_API_PORT}:${GRAM_API_PORT}
      - ${DOCS_PORT}:${DOCS_PORT}
      - ${NAV_PORT}:${NAV_PORT}
    environment:
      - IP=${IP}
      - GRAM_IP=${GRAM_IP}
      - RUNVALIDATOR=${RUNVALIDATOR}
      - RUNAPI=${RUNAPI}
      - RUNNAVIGATOR=${RUNNAVIGATOR}
      - DEPLOYTYPE=${DEPLOYTYPE}
      - TON_ENGINE_PORT=${TON_ENGINE_PORT}
      - LITESERVER_PORT=${LITESERVER_PORT}
      - JSON_EXPLORER_PORT=${JSON_EXPLORER_PORT}
      - NAV_PORT=${NAV_PORT}
      - CONSOLE_PORT=${CONSOLE_PORT}
      - GRAM_API_PORT=${GRAM_API_PORT}
      - DOCS_PORT=${DOCS_PORT}
      - WEB_EXPLORER_PORT=${WEB_EXPLORER_PORT}
      - VIZ_PORT=${VIZ_PORT}
      - JSON_EXPLORER_URI=${JSON_EXPLORER_URI}
      - GRAM_API_URI=${GRAM_API_URI}
      - TON_LOGLEVEL=${TON_LOGLEVEL}
      - DOTENV_CONFIG_PATH=/var/gram/.env
      - FIFTPATH=/var/gram/lib/fift:/var/gram/lib/smartcont
      - LS_PUB=/var/gram/profile/keys/liteserver.pub
      - PROFILE=/var/gram/profile
      - TON_SMARTCONT=/var/gram/lib/smartcont
      - NODETYPE=${NODETYPE}
      - GLOBALCONFIG=${GLOBALCONFIG}
      - IMAGEURI=${IMAGEURI} 
    volumes:
      - ./profile:/var/gram/profile
      - ./tondb:/var/gram/tondb
    deploy:
      placement:
        constraints:
          - node.role==manager
